export const projects = [
  {
    title: "Stock Analysis Report",
    description: `Stock analysis Power BI report built using data from equitieslist.com`,
    href: "https://www.youtube.com/watch?v=XZCLRacNBAw",
    mediaSrc: "/pbi-stock-dashboard-2.png",
    mediaType: "image",
  },
  {
    title: "Stock Analysis Report",
    description: `Stock analysis Power BI report built using data from equitieslist.com`,
    href: "https://www.youtube.com/watch?v=3vRH8DkPwQw",
    mediaSrc: "/pbi-stock-dashboard-1.png",
    mediaType: "image",
  },
  {
    title: "Real Estate Analysis Report",
    description: `Real Estate report built using data scraped from Zillow.com`,
    href: "https://github.com/JeremyPersing/zillow_dashboard",
    mediaSrc: "/real-estate-dashboard.png",
    mediaType: "image",
  },
  {
    title: "Equitieslist.com",
    description: `Stock analysis website. Built with Next.js, Typescript, Nodejs, and MongoDB.`,
    href: "/posts/revesta-net",
    mediaSrc: "/equitieslist/1.png",
    mediaType: "image",
  },
  {
    title: "Apartments.com Clone",
    description: `A clone of the Apartments.com mobile application. Built using Expo, React Native, Golang, and PostgreSQL.`,
    href: "https://github.com/JeremyPersing/apartmentsclone",
    mediaSrc: "/apartments-com-clone.png",
    mediaType: "image",
  },
  {
    title: "Project Javelin",
    description: `A mobile application built to follow the 2020 winter olympics. Built using Expo, React Native, Nodejs, and MongoDB.`,
    href: "/posts/projectjavelin",
    mediaSrc: "/projectjavelin.png",
    mediaType: "image",
  },
  {
    title: "Country Flags API",
    description: `An API built for developers to display country flags in their applications. Built using Nodejs and HTML.`,
    href: "/posts/country-flags-integration",
    mediaSrc: "/countryflags.jpg",
    mediaType: "image",
  },
  {
    title: "Skymail 3000",
    description: `A game I built for a college class. Built using Java and PowerPoint for the sprites.`,
    href: "/posts/skymail-3000",
    mediaSrc: "/heli.jpg",
    mediaType: "image",
  },
  {
    title: "Baby C Compiler",
    description: `A compiler I built for a college class. Built using C.`,
    href: "/posts/baby-c-compiler",
    mediaSrc: "/compiler.jpeg",
    mediaType: "image",
  },
  {
    title: "Analytics Project",
    description: `An analytics project I had to create with a classmate for a college class. Built using D3.`,
    href: "https://interactivedesign.surge.sh/",
    mediaSrc: "/visualization1.png",
    mediaType: "image",
  },
];
